AgendaCCB.Web/Models/CommonCongregationViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AgendaCCB.Web.Models
{
    public class CommonCongregationViewModel
    {
        public CommonCongregationViewModel()
        {

        }

        [DisplayName("Código")]
        public int Id { get; set; }

        [DisplayName("Nome Comum")]
        [Required(ErrorMessage = "É necessário informar um nome")]
        public string Name { get; set; }

        [DisplayName("Cidade")]
        [Required(ErrorMessage = "É necessário informar uma cidade")]
        public int IdCity { get; set; }

        [DisplayName("Endereço")]
        public string Address { get; set; }

        [DisplayName("Bairro")]
        public string District { get; set; }

        [DisplayName("CEP")]
        public string ZipCode { get; set; }

        [DisplayName("Telefone")]
        public string PhoneNumber { get; set; }

        [DisplayName("Fax")]
        public string FaxPhoneNumber { get; set; }

        public SelectList CityList { get; set; }
    }
}

AgendaCCB.Web/Controllers/CommonCongregationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendaCCB.Data.Models;
using AgendaCCB.Web.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;

namespace AgendaCCB.Web.Controllers
{
    public class CommonCongregationController : BaseController
    {
        public CommonCongregationController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor) : base(configuration, httpContextAccessor)
        {
        }

        // GET: CommonCongregation
        public IActionResult Index()
        {
            var commonCongregations = _context.CommonCongregation.Include(c => c.CityNavigation);
            return View(commonCongregations.ToList());
        }

        // GET: CommonCongregation/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commonCongregation = await _context.CommonCongregation
                .Include(c => c.CityNavigation)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (commonCongregation == null)
            {
                return NotFound();
            }

            return View(commonCongregation);
        }

        // GET: CommonCongregation/Create
        public IActionResult Create()
        {
            ViewBag.CityList = new SelectList(_context.City.Where(c => c.IdState == 26), "Id", "Name");
            return View();
        }

        // POST: CommonCongregation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CommonCongregationViewModel commonCongregationVM)
        {
            var commonCongregation = new CommonCongregation();
            if (ModelState.IsValid)
            {
                commonCongregation = MapTo(commonCongregationVM);
                _context.Add(commonCongregation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CityList = new SelectList(_context.City, "Id", "Name", commonCongregation.Id);
            return View(commonCongregation);
        }

        private CommonCongregation MapTo(CommonCongregationViewModel commonCongregationVM)
        {
            return new CommonCongregation()
            {
                IdCity = commonCongregationVM.IdCity,
                Name = commonCongregationVM.Name,
                Address = commonCongregationVM.Address,
                District = commonCongregationVM.District,
                FaxPhoneNumber = commonCongregationVM.FaxPhoneNumber,
                PhoneNumber = commonCongregationVM.PhoneNumber,
                ZipCode = commonCongregationVM.ZipCode
            };
        }

        // GET: CommonCongregation/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commonCongregation = await _context.CommonCongregation.SingleOrDefaultAsync(m => m.Id == id);
            if (commonCongregation == null)
            {
                return NotFound();
            }
            ViewBag.CityList = new SelectList(_context.City, "Id", "Name", commonCongregation.Id);
            return View(commonCongregation);
        }

        // POST: CommonCongregation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CommonCongregation commonCongregation)
        {
            if (id != commonCongregation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(commonCongregation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommonCongregationExists(commonCongregation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["Id"] = new SelectList(_context.City, "Id", "Name", commonCongregation.Id);
            return View(commonCongregation);
        }

        // GET: CommonCongregation/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commonCongregation = await _context.CommonCongregation
                .Include(c => c.CityNavigation)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (commonCongregation == null)
            {
                return NotFound();
            }

            return View(commonCongregation);
        }

        // POST: CommonCongregation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commonCongregation = await _context.CommonCongregation.SingleOrDefaultAsync(m => m.Id == id);
            _context.CommonCongregation.Remove(commonCongregation);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CommonCongregationExists(int id)
        {
            return _context.CommonCongregation.Any(e => e.Id == id);
        }
    }
}

AgendaCCB.Web/Views/CommonCongregation/Create.cshtml
@model AgendaCCB.Web.Models.CommonCongregationViewModel

@{
    ViewData["Title"] = "Criar Congregação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Comum Congregação</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "CommonCongregation")</li>
    <li class="breadcrumb-item active">Criar</li>
</ol>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Dados Congregação</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control phoneNumber" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.FaxPhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FaxPhoneNumber, new { htmlAttributes = new { @class = "form-control phoneNumber" } })
                        @Html.ValidationMessageFor(model => model.FaxPhoneNumber, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.IdCity, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.IdCity, ViewBag.CityList as IEnumerable<SelectListItem>, "Selecione...", htmlAttributes: new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.IdCity, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Criar" />
            <a href="@Url.Action("Index", "CommonCongregation")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

AgendaCCB.Web/Views/CommonCongregation/Delete.cshtml
@model AgendaCCB.Data.Models.CommonCongregation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes Congregação</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "CommonCongregation")</li>
    <li class="breadcrumb-item active">Detalhes</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados Congregação</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.FaxPhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.FaxPhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Address)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.District)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.District)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.ZipCode)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.ZipCode)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CityNavigation)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.CityNavigation.Name)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<h3>Tem certeza que deseja excluir?</h3>
@using (Html.BeginForm())
{
    <div class="form-actions">
        <input type="submit" value="Excluir" class="btn btn-danger btn-submit" />
        <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
    </div>
}

AgendaCCB.Web/Views/CommonCongregation/Details.cshtml
@model AgendaCCB.Data.Models.CommonCongregation

@{
    ViewData["Title"] = "Detalhes Congregação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Detalhes Congregação</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "CommonCongregation")</li>
    <li class="breadcrumb-item active">Detalhes</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados Congregação</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.FaxPhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.FaxPhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Address)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.District)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.District)
                    </td>
                </tr>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.ZipCode)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.ZipCode)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CityNavigation)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.CityNavigation.Name)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="form-actions">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-submit">Editar</a>
    <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
</div>

AgendaCCB.Web/Views/CommonCongregation/Edit.cshtml
@model AgendaCCB.Data.Models.CommonCongregation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Editar Colaborador</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "CommonCongregation")</li>
    <li class="breadcrumb-item active">Editar</li>
</ol>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        @Html.HiddenFor(model => model.Id)
        <div class="panel-heading">
            <h3 class="panel-title">Dados Congregação</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control phoneNumber" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.FaxPhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FaxPhoneNumber, new { htmlAttributes = new { @class = "form-control phoneNumber" } })
                        @Html.ValidationMessageFor(model => model.FaxPhoneNumber, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.IdCity, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.IdCity, ViewBag.CityList as IEnumerable<SelectListItem>, "Selecione...", htmlAttributes: new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.IdCity, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Salvar" />
            <a href="@Url.Action("Index", "CommonCongregation")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

AgendaCCB.Web/Views/CommonCongregation/Index.cshtml
@model IEnumerable<AgendaCCB.Data.Models.CommonCongregation>

@{
    ViewData["Title"] = "Lista de Congregações";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Lista de Congregações</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a asp-action="Create" class="close-link" title="Criar nova Congregação"><i class="fa fa-plus-circle"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>

        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdCityNavigation)
                        </th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdCityNavigation.Name)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" title="Editar"><i class="fa fa-edit"></i></a> |
                                <a asp-action="Details" asp-route-id="@item.Id" title="Detalhes"><i class="fa fa-eye"></i></a> |
                                <a asp-action="Delete" asp-route-id="@item.Id" title="Excluir"><i class="fa fa-remove"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>