AgendaCCB.Web/Models/AppAuthorizationToUseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaCCB.Web.Models
{
    public class AppAuthorizationToUseViewModel
    {
        public AppAuthorizationToUseViewModel()
        {

        }

        [DisplayName("Código")]
        public int Id { get; set; }

        [DisplayName("Número Telefone")]
        [Required(ErrorMessage = "É necessário informar um número de telefone")]
        public string PhoneNumber { get; set; }

        public string Token { get; set; }

        [DisplayName("Data Criação")]
        public DateTime Created { get; set; }

        [DisplayName("Usuário")]
        public string UserCreator { get; set; }

        [DisplayName("Usado?")]
        public bool Used { get; set; }
    }
}

AgendaCCB.Web/Controllers/AppauthorizationToUseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendaCCB.Data.Models;
using Microsoft.Extensions.Configuration;
using AgendaCCB.Web.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore.Query;
using AgendaCCB.Web.Models;

namespace AgendaCCB.Web.Controllers
{
    public class AppauthorizationToUseController : BaseController
    {
        public AppauthorizationToUseController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor) : base(configuration, httpContextAccessor)
        {
        }

        // GET: AppauthorizationToUse
        public IActionResult Index()
        {
            var agendaccbContext = _context.AppauthorizationToUse.Include(a => a.UserCreatorNavigation);
            var authorizationToUseVM = MapTo(agendaccbContext);
            return View(authorizationToUseVM);
        }

        // GET: AppauthorizationToUse/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appauthorizationToUse = _context.AppauthorizationToUse
                .Include(a => a.UserCreatorNavigation)
                .SingleOrDefault(m => m.Id == id);

            if (appauthorizationToUse == null)
            {
                return NotFound();
            }

            var authorizationToUseVM = MapTo(appauthorizationToUse);

            return View(authorizationToUseVM);
        }

        // GET: AppauthorizationToUse/Create
        public IActionResult Create()
        {
            AppAuthorizationToUseViewModel appauthorizationToUse = new AppAuthorizationToUseViewModel();            
            return View(appauthorizationToUse);
        }

        // POST: AppauthorizationToUse/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PhoneNumber,Token,Created,UserCreator,Used")] AppAuthorizationToUseViewModel appauthorizationToUse)
        {
            if (ModelState.IsValid)
            {
                _context.Add(MapTo(appauthorizationToUse));
                await _context.SaveChangesAsync();
                //SmsSenderExtensions.SendMessage(appauthorizationToUse.PhoneNumber, appauthorizationToUse.Token);
                return RedirectToAction(nameof(Index));
            }
            
            return View(appauthorizationToUse);
        }

        private string GenerateToken()
        {
            Random random = new Random();
            const string chars = "abcdefghijklmnopqrstuvxwyz0123456789";
            return new string(Enumerable.Repeat(chars, 8)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        // GET: AppauthorizationToUse/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appauthorizationToUse = await _context.AppauthorizationToUse.SingleOrDefaultAsync(m => m.Id == id);
            if (appauthorizationToUse == null)
            {
                return NotFound();
            }

            var authorizationToUseVM = MapTo(appauthorizationToUse);
            return View(authorizationToUseVM);
        }

        // POST: AppauthorizationToUse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PhoneNumber,Token,Created,UserCreator,Used")] AppAuthorizationToUseViewModel appauthorizationToUse)
        {
            if (id != appauthorizationToUse.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(MapTo(appauthorizationToUse));
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppauthorizationToUseExists(appauthorizationToUse.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserCreator"] = new SelectList(_context.AspNetUsers, "Id", "Id", appauthorizationToUse.UserCreator);
            return View(appauthorizationToUse);
        }

        // GET: AppauthorizationToUse/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appauthorizationToUse = await _context.AppauthorizationToUse
                .Include(a => a.UserCreatorNavigation)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (appauthorizationToUse == null)
            {
                return NotFound();
            }

            return View(MapTo(appauthorizationToUse));
        }

        // POST: AppauthorizationToUse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appauthorizationToUse = await _context.AppauthorizationToUse.SingleOrDefaultAsync(m => m.Id == id);
            _context.AppauthorizationToUse.Remove(appauthorizationToUse);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppauthorizationToUseExists(int id)
        {
            return _context.AppauthorizationToUse.Any(e => e.Id == id);
        }

        private List<AppAuthorizationToUseViewModel> MapTo(IIncludableQueryable<AppauthorizationToUse, AspNetUsers> agendaccbContext)
        {
            var ListAuthorization = new List<AppAuthorizationToUseViewModel>();

            foreach (var item in agendaccbContext)
            {
                ListAuthorization.Add(new AppAuthorizationToUseViewModel()
                {
                    Created = item.Created,
                    Id = item.Id,
                    PhoneNumber = item.PhoneNumber,
                    Token = item.Token,
                    Used = item.Used.Value,
                    UserCreator = item.UserCreatorNavigation.UserName
                });
            }

            return ListAuthorization;
        }

        private AppAuthorizationToUseViewModel MapTo(AppauthorizationToUse appauthorizationToUse)
        {
            return new AppAuthorizationToUseViewModel()
            {
                Created = appauthorizationToUse.Created,
                Id = appauthorizationToUse.Id,
                PhoneNumber = appauthorizationToUse.PhoneNumber,
                Token = appauthorizationToUse.Token,
                Used = appauthorizationToUse.Used.Value,
                UserCreator = appauthorizationToUse.UserCreator
            };
        }

        private AppauthorizationToUse MapTo(AppAuthorizationToUseViewModel appauthorizationToUse)
        {
            var token = string.IsNullOrEmpty(appauthorizationToUse.Token) ? GenerateToken() : appauthorizationToUse.Token;
            var userCreator = string.IsNullOrEmpty(appauthorizationToUse.UserCreator) ? _context.AspNetUsers.FirstOrDefault(us => us.Id == _userId).Id : _context.AspNetUsers.FirstOrDefault(us => us.Id == appauthorizationToUse.UserCreator).Id;
            var created = appauthorizationToUse.Created == new DateTime() ? DateTime.Now : appauthorizationToUse.Created;
            return new AppauthorizationToUse()
            {
                Created = created,
                Id = appauthorizationToUse.Id,
                PhoneNumber = appauthorizationToUse.PhoneNumber,
                Token = token,
                Used = appauthorizationToUse.Used,
                UserCreator = userCreator 
            };
        }
    }
}

AgendaCCB.Web/Views/AppauthorizationToUse/Create.cshtml
@model AgendaCCB.Web.Models.AppAuthorizationToUseViewModel

@{
    ViewData["Title"] = "Liberar Uso APP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Autorização Aplicativo Agenda</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "AppauthorizationToUse")</li>
    <li class="breadcrumb-item active">Criar</li>
</ol>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Liberação uso aplicativo</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">                                                                      
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>                    
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Gerar" />
            <a href="@Url.Action("Index", "AppauthorizationToUse")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

AgendaCCB.Web/Views/AppauthorizationToUse/Delete.cshtml
@model AgendaCCB.Web.Models.AppAuthorizationToUseViewModel

@{
    ViewData["Title"] = "Remover autorização APP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Remover autorização APP</h2>
<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "AppauthorizationToUse")</li>
    <li class="breadcrumb-item active">Detalhes</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados autorização APP</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Token)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Token)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Created)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Created)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Used)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Used)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.UserCreator)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.UserCreator)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<h3>Tem certeza que deseja remover?</h3>
@using (Html.BeginForm())
{
    <div class="form-actions">
        <input type="submit" value="Excluir" class="btn btn-danger btn-submit" />
        <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
    </div>
}

AgendaCCB.Web/Views/AppauthorizationToUse/Details.cshtml
@model AgendaCCB.Web.Models.AppAuthorizationToUseViewModel
@{
    ViewData["Title"] = "Detalhes Liberação APP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Detalhes Liberação APP</h2>
<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "AppauthorizationToUse")</li>
    <li class="breadcrumb-item active">Detalhes</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados autorização APP</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Token)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Token)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Created)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Created)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Used)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Used)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.UserCreator)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.UserCreator)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="form-actions">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-submit">Editar</a>
    <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
</div>

AgendaCCB.Web/Views/AppauthorizationToUse/Edit.cshtml
@model AgendaCCB.Web.Models.AppAuthorizationToUseViewModel
@{
    ViewData["Title"] = "Editar Liberação Uso APP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Editar Autorização Aplicativo Agenda</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "AppauthorizationToUse")</li>
    <li class="breadcrumb-item active">Editar</li>
</ol>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Liberação uso aplicativo</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.HiddenFor(model => model.Created)
                        @Html.HiddenFor(model => model.UserCreator)
                        @Html.HiddenFor(model =>model.Token)
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-6">                        
                        @Html.LabelFor(model => model.Used, htmlAttributes: new { @class = "control-label" })
                        @Html.CheckBoxFor(model => model.Used, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Used, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Salvar" />
            <a href="@Url.Action("Index", "AppauthorizationToUse")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

AgendaCCB.Web/Views/AppauthorizationToUse/Index.cshtml
@model IEnumerable<AgendaCCB.Web.Models.AppAuthorizationToUseViewModel>
@{
    ViewData["Title"] = "Lista de liberações do APP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Lista de liberações do APP</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a asp-action="Create" class="close-link" title="Criar novo Cargo/Ministério"><i class="fa fa-plus-circle"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Token)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Created)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Used)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UserCreator)
                        </th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Token)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Created)
                            </td>
                            <td>
                                @{ var usado = item.Used == true ? "Sim" : "Não";}
                                @usado
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserCreator)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" title="Editar"><i class="fa fa-edit"></i></a> |
                                <a asp-action="Details" asp-route-id="@item.Id" title="Detalhes"><i class="fa fa-eye"></i></a> |
                                <a asp-action="Delete" asp-route-id="@item.Id" title="Excluir"><i class="fa fa-remove"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>