AgendaCCB.Web/Models/CollaboratorViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AgendaCCB.Web.Models
{
    public class CollaboratorViewModel
    {
        public CollaboratorViewModel()
        {

        }

        public CollaboratorViewModel(CollaboratorViewModel collaboratorViewModel)
        {
            Id = collaboratorViewModel.Id;
            Name = collaboratorViewModel.Name;
            IdPositionMinistry = collaboratorViewModel.IdPositionMinistry;
            IdCommonCongregation = collaboratorViewModel.IdCommonCongregation;
        }

        [DisplayName("Código Colaborador")]
        public int Id { get; set; }

        [DisplayName("Nome Colaborador")]
        [Required(ErrorMessage = "É necessário informar um nome")]
        public string Name { get; set; }

        [DisplayName("Cargo / Ministério")]
        public int? IdPositionMinistry { get; set; }

        [DisplayName("Telefone")]
        public int? IdPhoneNumber { get; set; }

        [DisplayName("Tipo")]
        public int? TypePhone { get; set; }

        [DisplayName("Telefone")]
        public List<PhoneNumberViewModel> PhoneNumberList { get; set; }

        [DisplayName("Cargo")]
        public List<PositionMinistryViewModel> PositionMinistryList { get; set; }

        public SelectList TypePhoneList { get; set; }

        [DisplayName("Comum Congregação")]
        [Required(ErrorMessage = "É necessário informar a comum Congregação")]
        public int IdCommonCongregation { get; set; }
    }
}

AgendaCCB.Web/Controllers/CollaboratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendaCCB.Data.Models;
using AgendaCCB.Web.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;

namespace AgendaCCB.Web.Controllers
{
    public class CollaboratorController : BaseController
    {
        public CollaboratorController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor) : base(configuration, httpContextAccessor)
        {
        }
        
        // GET: Collaborator
        public async Task<IActionResult> Index()
        {
            var collaborators = _context.GetAllColaborators();

            return View(await collaborators.ToListAsync());
        }

        // GET: Collaborator/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collaborator = _context.GetCollaboratorById(id);
                
            if (collaborator == null)
            {
                return NotFound();
            }

            return View(await collaborator);
        }

        // GET: Collaborator/Create
        public IActionResult Create()
        {
            ViewBag.CommonList = _context.CommonCongregation.Select(p => new SelectListItem
            {
                Text = p.Name + "-" + p.CityNavigation.Name,
                Value = p.Id.ToString()
            }).OrderBy(c => c.Text);
            ViewBag.PositionMinistryList = new SelectList(_context.PositionMinistry, "Id", "Description").OrderBy(p => p.Text);
            ViewBag.TypePhoneList = EnumHelper<TypePhone>.GetSelectListEnum();

            return View();
        }

        // POST: Collaborator/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CollaboratorViewModel collaboratorVM)
        {
            if (ModelState.IsValid)
            {
                Collaborator collaborator = this.MapTo(collaboratorVM);
                _context.Add(collaborator);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Registro inserido com sucesso";
                return RedirectToAction("Index");
            }

            ViewBag.CommonList = _context.CommonCongregation.Select(c => new SelectListItem
            {
                Text = c.Name + " - " + c.CityNavigation.Name,
                Value = c.Id.ToString(),
                Selected = c.Id == collaboratorVM.IdCommonCongregation                
            }).OrderBy(c => c.Text);
            
            ViewBag.PositionMinistryList = new SelectList(_context.PositionMinistry, "Id", "Description", collaboratorVM.IdPositionMinistry).OrderBy(p => p.Text);
            ViewBag.TypePhoneList = EnumHelper<TypePhone>.GetSelectListEnum();

            return View(collaboratorVM);
        }

        // GET: Collaborator/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collaborator = await _context.GetCollaboratorById(id);
            if (collaborator == null)
            {
                return NotFound();
            }

            var collaboratorVM = MapTo(collaborator);

            ViewBag.CommonList = _context.CommonCongregation.Select(p => new SelectListItem
            {
                Text = p.Name + " - " + p.CityNavigation.Name,
                Value = p.Id.ToString(),
                Selected = p.Id == collaboratorVM.IdCommonCongregation
            }).OrderBy(c => c.Text);

            ViewBag.PositionMinistryList = new SelectList(_context.PositionMinistry, "Id", "Description", collaboratorVM.IdPositionMinistry).OrderBy(p => p.Text);
            ViewBag.TypePhoneList = EnumHelper<TypePhone>.GetSelectListEnum();
            
            return View(collaboratorVM);
        }

        // POST: Collaborator/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CollaboratorViewModel collaboratorVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var collaborator = MapTo(collaboratorVM);

                    var oldPhoneNumbersObj = _context.PhoneNumber.AsNoTracking()
                        .Where(pn => pn.IdCollaborador == collaborator.Id && !collaborator.PhoneNumber.Select(p => p.Id).Contains(pn.Id));

                    var oldPositionMinistryObj = _context.PositionMinistryCollaborator.AsNoTracking()
                        .Where(pmc => pmc.IdCollaborator == collaborator.Id && !collaborator.PositionMinistryCollaborator.Select(p => p.Id).Contains(pmc.Id));

                    foreach (var phoneNumber in collaborator.PhoneNumber)
                    {
                        if (phoneNumber.Id == new int())
                            _context.PhoneNumber.Add(phoneNumber);
                        else
                            _context.PhoneNumber.Update(phoneNumber);
                    }

                    foreach (var oldPhoneNumber in oldPhoneNumbersObj)
                    {
                        _context.PhoneNumber.Remove(oldPhoneNumber);
                    }

                    foreach (var positionMinistry in collaborator.PositionMinistryCollaborator)
                    {
                        if (positionMinistry.Id == new int())
                            _context.PositionMinistryCollaborator.Add(positionMinistry);
                        else
                            _context.PositionMinistryCollaborator.Update(positionMinistry);
                    }

                    foreach (var oldPositionMinistry in oldPositionMinistryObj)
                    {
                        _context.PositionMinistryCollaborator.Remove(oldPositionMinistry);
                    }

                    _context.Update(collaborator);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CollaboratorExists(collaboratorVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Success"] = "Registro alterado com sucesso";
                return RedirectToAction("Index");
            }
            ViewBag.CommonList = _context.CommonCongregation.Select(p => new SelectListItem
            {
                Text = p.Name + "-" + p.CityNavigation.Name,
                Value = p.Id.ToString(),
                Selected = p.Id == collaboratorVM.IdCommonCongregation
            });

            ViewData["IdPositionMinistry"] = new SelectList(_context.PositionMinistry, "Id", "Description", collaboratorVM.IdPositionMinistry);
            return View(collaboratorVM);
        }

        // GET: Collaborator/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collaborator = _context.GetCollaboratorById(id);

            if (collaborator == null)
            {
                return NotFound();
            }

            return View(await collaborator);
        }

        // POST: Collaborator/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var collaborator = await _context.Collaborator.SingleOrDefaultAsync(m => m.Id == id);

            var phoneNumbers = _context.PhoneNumber.Where(m => m.IdCollaborador == id);

            var positionMinistry = _context.PositionMinistryCollaborator.Where(pm => pm.IdCollaborator == id);

            foreach (var item in phoneNumbers)
            {
                _context.PhoneNumber.Remove(item);
            }

            foreach (var item in positionMinistry)
            {
                _context.PositionMinistryCollaborator.Remove(item);
            }

            _context.Collaborator.Remove(collaborator);
            await _context.SaveChangesAsync();
            TempData["Success"] = "Registro removido com sucesso";
            return RedirectToAction("Index");
        }

        private bool CollaboratorExists(int id)
        {
            return _context.Collaborator.Any(e => e.Id == id);
        }

        private Collaborator MapTo(CollaboratorViewModel collaboratorVM)
        {
            Collaborator collaborator = new Collaborator();

            collaborator.IdCommonCongregation = collaboratorVM.IdCommonCongregation;            
            collaborator.Name = collaboratorVM.Name;
            collaborator.Id = collaboratorVM.Id;

            collaborator.PhoneNumber = new List<PhoneNumber>();
            collaborator.PositionMinistryCollaborator = new List<PositionMinistryCollaborator>();

            foreach (var phone in collaboratorVM.PhoneNumberList)
            {
                collaborator.PhoneNumber.Add(new PhoneNumber()
                {
                    Number = phone.Phone,
                    Type = phone.TypePhone.ToString(),
                    IdCollaborador = collaboratorVM.Id,
                    Id = phone.Id                    
                });
            }

AgendaCCB.Web/Views/Collaborator/Create.cshtml
@model AgendaCCB.Web.Models.CollaboratorViewModel

@{
    ViewData["Title"] = "Criar Colaborador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Colaborador</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "Collaborator")</li>
    <li class="breadcrumb-item active">Criar</li>
</ol>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Dados Colaborador</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.IdCommonCongregation, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.IdCommonCongregation, ViewBag.CommonList as IEnumerable<SelectListItem>, "Selecione...", htmlAttributes: new { @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.IdCommonCongregation, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-md-6">
                        @Html.LabelFor(model => model.IdPositionMinistry, htmlAttributes: new { @class = "control-label" })
                        <div class="input-group">
                            @Html.DropDownListFor(model => model.IdPositionMinistry, ViewBag.PositionMinistryList as IEnumerable<SelectListItem>, "Selecione...", htmlAttributes: new { @class = "form-control", @required="required" })
                            <span class="input-group-addon" id="addPositionMinistry"><i class="glyphicon glyphicon-plus"></i></span>
                        </div>
                        @Html.ValidationMessageFor(model => model.IdPositionMinistry, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-12 col-md-6">
                        @Html.Label("", "Lista de Cargos / Ministérios", htmlAttributes: new { @class = "control-label" })
                        <table class="table table-bordered table-striped" style="margin-bottom:0px !important">
                            <tbody id="positionMinistryList">
                                <tr id="0">
                                    <td>
                                        Nenhum item inserido
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-md-4">
                        @Html.LabelFor(model => model.TypePhone, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.TypePhone, ViewBag.TypePhoneList as IEnumerable<SelectListItem>, "Selecione...", htmlAttributes: new { @class = "form-control", @required="required" })
                        @Html.ValidationMessageFor(model => model.TypePhone, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-12 col-md-4">
                        @Html.LabelFor(model => model.IdPhoneNumber, htmlAttributes: new { @class = "control-label" })
                        <div class="input-group">
                            @Html.TextBox("PhoneNumber", "", new { @class = "form-control phoneNumber", @required = "required" })
                            <span class="input-group-addon" id="addPhoneNumber"><i class="glyphicon glyphicon-plus"></i></span>
                        </div>
                        @Html.ValidationMessage("PhoneNumber", "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-12 col-md-4">
                        @Html.Label("", "Lista de Telefones", htmlAttributes: new { @class = "control-label" })
                        <table class="table table-bordered table-striped" style="margin-bottom:0px !important">
                            <tbody id="phoneNumberList">
                                <tr id="0">
                                    <td>
                                        Nenhum item inserido
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Criar" />
            <a href="@Url.Action("Index", "Collaborator")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

@section Scripts {
    <script type="text/javascript">
        //Phone Number Scripts

        $("#addPhoneNumber").click(function (e) {
            var $phoneNumber = $("#PhoneNumber");
            var $typePhone = $("#TypePhone");

            if (!$phoneNumber.val() || !$typePhone.val()) {
                $phoneNumber.attr('required', 'required');
                $typePhone.attr('required', 'required');

                var validator = $("form").validate();
                validator.element($phoneNumber);
                validator.element($typePhone);

                return;
            }

            $phoneNumberList = $("#phoneNumberList");
            if ($phoneNumberList.find('tr#0').length == 1) {
                $tr = $phoneNumberList.find('tr');
                $tr.remove();
            }

            if ($phoneNumberList.find('tr#' + $typePhone.val()).length == 0) {
                var $index = $phoneNumberList.children().last().index();
                if ($index == -1)
                    $index = 0;
                else
                    $index = $index + 1;

                var $element = "<tr id='" + $typePhone.val() + "'>"
                    + "<input type= 'hidden' id= 'PhoneNumberList_" + $index + "__Phone' name= 'PhoneNumberList[" + $index + "].Phone' value= '" + $phoneNumber.val() + "'>"
                    + "<input type= 'hidden' id= 'PhoneNumberList_" + $index + "__TypePhone' name= 'PhoneNumberList[" + $index + "].TypePhone' value= '" + $typePhone.val() + "'>"
                    + "<td>" + $phoneNumber.val() + " - " + $typePhone.find("option:selected").text()
                    + "<span style='float:right;'><i class='glyphicon glyphicon-remove' onclick='removeElement(this);'></i></span></td > "
                    + "</tr > ";
                $phoneNumberList.append($element)

                $("#PhoneNumber").val("");
                $("#TypePhone").val("");                
            }
            validatePhoneNumberList();
        });

        function validatePhoneNumberList() {
            $tableCategories = $('#phoneNumberListtr[id="0"]').length;

            if ($tableCategories == 1) {
                $('#TypePhone').prop("required", true);
                $('#PhoneNumber').prop("required", true);           
                return true;
            } else {
                $('#TypePhone').prop("required", false);
                $('#PhoneNumber').prop("required", false);
                return false;
            }         
        }

        function removeElement(element) {
            $element = $(element).parents('tr');
            $element.remove();

            $phoneNumberList = $("#phoneNumberList");
            if ($phoneNumberList.children().length == 0) {
                var $phoneNumber = $("#PhoneNumber");
                var $typePhone = $("#TypePhone");
                $phoneNumber.attr('required', 'required');
                $typePhone.attr('required', 'required');
                var $element = "<tr id='0'><td>Nenhum item inserido</td></tr>";
                $phoneNumberList.append($element);
            } else {
                updatePosition($phoneNumberList);
            }
        }

        function updatePosition(phoneNumberList) {
            $(phoneNumberList).children().each(function (i) {
                var $this = $(this).children('input');
                $this.attr("name", "PhoneNumberList[" + i + "].Phone");
                $this.attr("id", "PhoneNumberList" + i + "__Phone");
                $this.attr("name", "PhoneNumberList[" + i + "].TypePhone");
                $this.attr("id", "PhoneNumberList" + i + "__TypePhone");
            });
        }


        //Position Ministry Scripts

        $("#addPositionMinistry").click(function (e) {
            var $positionMinistry = $("#IdPositionMinistry");

            if (!$positionMinistry.val()) {
                $positionMinistry.attr('required', 'required');

                var validator = $("form").validate();
                validator.element($positionMinistry);

                return;
            }

            $positionMinistryList = $("#positionMinistryList");
            if ($positionMinistryList.find('tr#0').length == 1) {
                $tr = $positionMinistryList.find('tr');
                $tr.remove();
            }

            if ($positionMinistryList.find('tr#' + $positionMinistry.val()).length == 0) {
                var $index = $positionMinistryList.children().last().index();
                if ($index == -1)
                    $index = 0;
                else
                    $index = $index + 1;

                var $element = "<tr id='" + $positionMinistry.val() + "'>"
                    + "<input type= 'hidden' id= 'PositionMinistryList_" + $index + "__Id' name= 'PositionMinistryList[" + $index + "].Id' value= '" + $positionMinistry.val() + "'>"
                    + "<input type= 'hidden' id= 'PositionMinistryList_" + $index + "__Description' name= 'PositionMinistryList[" + $index + "].Description' value= '" + $positionMinistry.find("option:selected").text() + "'>"
                    + "<td>" + $positionMinistry.find("option:selected").text()
                    + "<span style='float:right;'><i class='glyphicon glyphicon-remove' onclick='removePositionMinistry(this);'></i></span></td > "
                    + "</tr > ";
                $positionMinistryList.append($element)

                $("#IdPositionMinistry").val("");
            }
            validatePositionMinistryList();
        });

        function validatePositionMinistryList() {
            $tablePositionMinistry = $('#positionMinistryList tr[id="0"]').length;

            if ($tablePositionMinistry == 1) {
                $('#IdPositionMinistry').prop("required", true);
                return true;
            } else {
                $('#IdPositionMinistry').prop("required", false);
                return false;
            }
        }

        function removePositionMinistry(element) {
            $element = $(element).parents('tr');
            $element.remove();

            $positionMinistryList = $("#positionMinistryList");
            if ($positionMinistryList.children().length == 0) {
                var $positionMinistry = $("#IdPositionMinistry");
                $positionMinistry.attr('required', 'required');
                var $element = "<tr id='0'><td>Nenhum item inserido</td></tr>";
                $positionMinistryList.append($element);
            } else {
                updatePositionMinistry($positionMinistryList);
            }
        }

        function updatePositionMinistry(positionMinistryList) {
            $(positionMinistryList).children().each(function (i) {

                var $thisElementPosition = $(this).children('input');
                var index = i;
                $thisElementPosition.each(function (i, elem) {
                    var $this = elem.id;

                    if (~$this.indexOf("__Description")) {
                        $this.attr("name", "PositionMinistryList[" + i + "].Description");
                        $this.attr("id", "PositionMinistryList_" + i + "__Description");
                    } else {
                        $this.attr("name", "PositionMinistryList[" + i + "].Id");
                        $this.attr("id", "PositionMinistryList_" + i + "__Id");
                    }
                });
            });
        }

    </script>
}

AgendaCCB.Web/Views/Collaborator/Delete.cshtml
@model AgendaCCB.Data.Models.Collaborator

@{
    ViewData["Title"] = "Excluir Colaborador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes Colaborador</h2>


<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "Collaborator")</li>
    <li class="breadcrumb-item active">Detalhes</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados Colaborador</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>

                    <td>
                        @foreach (var item in Model.PhoneNumber)
                        {
                            @Html.DisplayFor(model => item.Number)
                            <br />
                        }
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdCommonCongregationNavigation)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.IdCommonCongregationNavigation.Name)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PositionMinistryCollaborator)
                    </th>
                    <td>
                        @foreach (var item in Model.PositionMinistryCollaborator)
                        {
                            @Html.DisplayFor(model => item.IdPositionMinistryNavigation.Description)
                            <br />
                        }
                    </td>
                </tr>
        </table>
    </div>
</div>
<h3>Tem certeza que deseja excluir?</h3>
@using (Html.BeginForm())
{
    <div class="form-actions">
        <input type="submit" value="Excluir" class="btn btn-danger btn-submit" />
        <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
    </div>
}

AgendaCCB.Web/Views/Collaborator/Details.cshtml
@model AgendaCCB.Data.Models.Collaborator

@{
    ViewData["Title"] = "Detalhes Colaborador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes Colaborador</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "Collaborator")</li>
    <li class="breadcrumb-item active">Detalhes Colaborador</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados Colaborador</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>

                    <td>
                        @foreach (var item in Model.PhoneNumber)
                        {
                            @Html.DisplayFor(model => item.Number)
                            <br />
                        }
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdCommonCongregationNavigation)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.IdCommonCongregationNavigation.Name)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PositionMinistryCollaborator)
                    </th>
                    <td>
                        @foreach (var item in Model.PositionMinistryCollaborator)
                        {
                            @Html.DisplayFor(model => item.IdPositionMinistryNavigation.Description)
                            <br />
                        }
                    </td>
                </tr>
        </table>
    </div>
</div>

<div class="form-actions">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-submit">Editar</a>
    <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
</div>