AgendaCCB.Web/Controllers/UsefulPhoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendaCCB.Data.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;

namespace AgendaCCB.Web.Controllers
{
    public class UsefulPhoneController : BaseController
    {
        public UsefulPhoneController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor) : base(configuration, httpContextAccessor)
        {
        }

        // GET: UsefulPhone
        public async Task<IActionResult> Index()
        {
            return View(await _context.UsefulPhone.ToListAsync());
        }

        // GET: UsefulPhone/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usefulPhone = await _context.UsefulPhone
                .SingleOrDefaultAsync(m => m.Id == id);
            if (usefulPhone == null)
            {
                return NotFound();
            }

            return View(usefulPhone);
        }

        // GET: UsefulPhone/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UsefulPhone/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LocalName,PhoneNumber")] UsefulPhone usefulPhone)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usefulPhone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usefulPhone);
        }

        // GET: UsefulPhone/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usefulPhone = await _context.UsefulPhone.SingleOrDefaultAsync(m => m.Id == id);
            if (usefulPhone == null)
            {
                return NotFound();
            }
            return View(usefulPhone);
        }

        // POST: UsefulPhone/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LocalName,PhoneNumber")] UsefulPhone usefulPhone)
        {
            if (id != usefulPhone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usefulPhone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsefulPhoneExists(usefulPhone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usefulPhone);
        }

        // GET: UsefulPhone/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usefulPhone = await _context.UsefulPhone
                .SingleOrDefaultAsync(m => m.Id == id);
            if (usefulPhone == null)
            {
                return NotFound();
            }

            return View(usefulPhone);
        }

        // POST: UsefulPhone/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usefulPhone = await _context.UsefulPhone.SingleOrDefaultAsync(m => m.Id == id);
            _context.UsefulPhone.Remove(usefulPhone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsefulPhoneExists(int id)
        {
            return _context.UsefulPhone.Any(e => e.Id == id);
        }
    }
}

AgendaCCB.Web/Views/UsefulPhone/Create.cshtml
@model AgendaCCB.Data.Models.UsefulPhone

@{
    ViewData["Title"] = "Criar Telefones Úteis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Telefones Úteis</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "UsefulPhone")</li>
    <li class="breadcrumb-item active">Criar</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Dados Telefones Úteis</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.LocalName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.LocalName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LocalName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control phoneNumber" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Criar" />
            <a href="@Url.Action("Index", "UsefulPhone")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

AgendaCCB.Web/Views/UsefulPhone/Delete.cshtml
@model AgendaCCB.Data.Models.UsefulPhone
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Detalhes Telefone Útil</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "UsefulPhone")</li>
    <li class="breadcrumb-item active">Excluir</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados Telefone Útil</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.LocalName)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.LocalName)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<h3>Tem certeza que deseja excluir?</h3>
@using (Html.BeginForm())
{
    <div class="form-actions">
        <input type="submit" value="Excluir" class="btn btn-danger btn-submit" />
        <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
    </div>
}

AgendaCCB.Web/Views/UsefulPhone/Details.cshtml
@model AgendaCCB.Data.Models.UsefulPhone
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes Telefones Úteis</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "UsefulPhone")</li>
    <li class="breadcrumb-item active">Detalhes</li>
</ol>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Dados Telefones Úteis</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="col-md-3">
                        @Html.DisplayNameFor(model => model.LocalName)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.LocalName)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="form-actions">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-submit">Editar</a>
    <a href="@Url.Action("Index")" class="btn btn-default">Voltar para a Lista</a>
</div>

AgendaCCB.Web/Views/UsefulPhone/Edit.cshtml
@model AgendaCCB.Data.Models.UsefulPhone

@{
    ViewData["Title"] = "Criar Telefones Úteis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Telefones Úteis</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Index", "Index", "UsefulPhone")</li>
    <li class="breadcrumb-item active">Editar</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Dados Telefones Úteis</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.LocalName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.LocalName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LocalName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control phoneNumber" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="panel-footer">
            <input type="submit" class="btn btn-primary btn-submit" value="Salvar" />
            <a href="@Url.Action("Index", "UsefulPhone")" class="btn btn-default">Cancelar</a>
        </div>
    </div>
}

AgendaCCB.Web/Views/UsefulPhone/Index.cshtml
@model IEnumerable<AgendaCCB.Data.Models.UsefulPhone>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Lista de Cargos/Ministérios</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a asp-action="Create" class="close-link" title="Criar novo Cargo/Ministério"><i class="fa fa-plus-circle"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.LocalName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.LocalName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" title="Editar"><i class="fa fa-edit"></i></a> |
                                <a asp-action="Details" asp-route-id="@item.Id" title="Detalhes"><i class="fa fa-eye"></i></a> |
                                <a asp-action="Delete" asp-route-id="@item.Id" title="Excluir"><i class="fa fa-remove"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>